### ISSUE TITLE
How to set start/end time for run

### ISSUE THREAD

**Issue by kkappler** [simpeg/aurora#188]
When working with synthetic data, the default start time of a run is `1980-01-01T00:00:00+00:00`

But if you want to tell mth5 that the run should start at a different time, how is that done?

Tried manually changing `runts.run_metadata.time_period.start` but no joy.

Example can be found in `aurora/test_utils/synthetic/make_mth5_from_asc.py`
`create_test3_h5`

I created a `fix_issue_188` branch with a few things I was trying.

**Comment by kujaku11** [comment]
@kkappler I pushed a slight adjustment to making synthetic MTH5 files.  There are a few things to keep in mind:

- The runts metadata will overwrite any previous `Run.metadata` so setting the run start time is mute.  
- The `run_group.metadata` start and end time are dictated by the channel's start and end time, so if you want new start and end times you should do that at the channel level.  I added that into 'create_run_ts_from_synthetic_run' so just change the start time in the `aurora\test_utils\synthetic\synthetic_station_config.py`
- When overwriting metadata in an H5 group be sure to run the method `write_metadata` after the change so that it will be written to the MTH5.  

Hopefully that helps

**Comment by kkappler** [comment]
This has been addressed on branch `fix_issue_188_2`

Deleting the old fix_issue_188 branch
